/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppointmentRequest {
  'id' : bigint,
  'service' : ServiceType,
  'email' : string,
  'message' : string,
  'preferredDate' : Time,
  'timestamp' : Time,
  'patientName' : string,
  'phone' : string,
}
export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type ServiceType = { 'filling' : null } |
  { 'braces' : null } |
  { 'whitening' : null } |
  { 'cleaning' : null } |
  { 'implants' : null } |
  { 'extractions' : null } |
  { 'consultation' : null };
export type Time = bigint;
export interface _SERVICE {
  'bookAppointment' : ActorMethod<
    [string, string, string, Time, ServiceType, string],
    bigint
  >,
  'getAllAppointments' : ActorMethod<[], Array<AppointmentRequest>>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAppointment' : ActorMethod<[bigint], AppointmentRequest>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];