/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ServiceType = IDL.Variant({
  'filling' : IDL.Null,
  'braces' : IDL.Null,
  'whitening' : IDL.Null,
  'cleaning' : IDL.Null,
  'implants' : IDL.Null,
  'extractions' : IDL.Null,
  'consultation' : IDL.Null,
});
export const AppointmentRequest = IDL.Record({
  'id' : IDL.Nat,
  'service' : ServiceType,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : Time,
  'timestamp' : Time,
  'patientName' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, ServiceType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(AppointmentRequest)], ['query']),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAppointment' : IDL.Func([IDL.Nat], [AppointmentRequest], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ServiceType = IDL.Variant({
    'filling' : IDL.Null,
    'braces' : IDL.Null,
    'whitening' : IDL.Null,
    'cleaning' : IDL.Null,
    'implants' : IDL.Null,
    'extractions' : IDL.Null,
    'consultation' : IDL.Null,
  });
  const AppointmentRequest = IDL.Record({
    'id' : IDL.Nat,
    'service' : ServiceType,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : Time,
    'timestamp' : Time,
    'patientName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, ServiceType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllAppointments' : IDL.Func(
        [],
        [IDL.Vec(AppointmentRequest)],
        ['query'],
      ),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAppointment' : IDL.Func([IDL.Nat], [AppointmentRequest], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };