/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AppointmentRequest {
    id: bigint;
    service: ServiceType;
    email: string;
    message: string;
    preferredDate: Time;
    timestamp: Time;
    patientName: string;
    phone: string;
}
export interface ContactForm {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export type Time = bigint;
export enum ServiceType {
    filling = "filling",
    braces = "braces",
    whitening = "whitening",
    cleaning = "cleaning",
    implants = "implants",
    extractions = "extractions",
    consultation = "consultation"
}
export interface backendInterface {
    bookAppointment(patientName: string, phone: string, email: string, preferredDate: Time, service: ServiceType, message: string): Promise<bigint>;
    getAllAppointments(): Promise<Array<AppointmentRequest>>;
    getAllContactForms(): Promise<Array<ContactForm>>;
    getAppointment(id: bigint): Promise<AppointmentRequest>;
    submitContactForm(name: string, email: string, message: string): Promise<void>;
}
import type { AppointmentRequest as _AppointmentRequest, ServiceType as _ServiceType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bookAppointment(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: ServiceType, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, to_candid_ServiceType_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, to_candid_ServiceType_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<AppointmentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactForms(): Promise<Array<ContactForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactForms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactForms();
            return result;
        }
    }
    async getAppointment(arg0: bigint): Promise<AppointmentRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_AppointmentRequest_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_AppointmentRequest_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AppointmentRequest_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentRequest): AppointmentRequest {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    service: _ServiceType;
    email: string;
    message: string;
    preferredDate: _Time;
    timestamp: _Time;
    patientName: string;
    phone: string;
}): {
    id: bigint;
    service: ServiceType;
    email: string;
    message: string;
    preferredDate: Time;
    timestamp: Time;
    patientName: string;
    phone: string;
} {
    return {
        id: value.id,
        service: from_candid_ServiceType_n6(_uploadFile, _downloadFile, value.service),
        email: value.email,
        message: value.message,
        preferredDate: value.preferredDate,
        timestamp: value.timestamp,
        patientName: value.patientName,
        phone: value.phone
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filling: null;
} | {
    braces: null;
} | {
    whitening: null;
} | {
    cleaning: null;
} | {
    implants: null;
} | {
    extractions: null;
} | {
    consultation: null;
}): ServiceType {
    return "filling" in value ? ServiceType.filling : "braces" in value ? ServiceType.braces : "whitening" in value ? ServiceType.whitening : "cleaning" in value ? ServiceType.cleaning : "implants" in value ? ServiceType.implants : "extractions" in value ? ServiceType.extractions : "consultation" in value ? ServiceType.consultation : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppointmentRequest>): Array<AppointmentRequest> {
    return value.map((x)=>from_candid_AppointmentRequest_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    filling: null;
} | {
    braces: null;
} | {
    whitening: null;
} | {
    cleaning: null;
} | {
    implants: null;
} | {
    extractions: null;
} | {
    consultation: null;
} {
    return value == ServiceType.filling ? {
        filling: null
    } : value == ServiceType.braces ? {
        braces: null
    } : value == ServiceType.whitening ? {
        whitening: null
    } : value == ServiceType.cleaning ? {
        cleaning: null
    } : value == ServiceType.implants ? {
        implants: null
    } : value == ServiceType.extractions ? {
        extractions: null
    } : value == ServiceType.consultation ? {
        consultation: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
